[mypy]
mypy_path = backend
explicit_package_bases = True

plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

strict_optional = True
check_untyped_defs = True

[mypy.plugins.django-stubs]
django_settings_module = "community_sharing.settings"
