/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categories/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_all_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chat_conversations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chat_conversations_messages_list"];
        put?: never;
        post: operations["chat_conversations_messages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description A beszélgetésben lévő, a másik fél által küldött olvasatlan üzenetek olvasottá tétele. */
        post: operations["chat_conversations_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_all_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["items_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/delete/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["items_delete_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/edit/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["items_edit_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["items_edit_partial_update"];
        trace?: never;
    };
    "/api/reservations/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reservations_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/get/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reservations_get_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/get/requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reservations_get_requests_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reservations_update_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reservations_update_partial_update"];
        trace?: never;
    };
    "/api/reviews/{reservation_id}/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviews_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/suspend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["users_suspend_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_suspend_partial_update"];
        trace?: never;
    };
    "/api/users/add_location/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_add_location_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_all_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/delete_location/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["users_delete_location_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/edit_location/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["users_edit_location_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_edit_location_partial_update"];
        trace?: never;
    };
    "/api/users/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_items_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/locations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_locations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_refresh_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/reviews/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_reviews_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/update_profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["users_update_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_update_profile_partial_update"];
        trace?: never;
    };
    "/api/users/update_profilepic/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["users_update_profilepic_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_update_profilepic_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddEditLocation: {
            label?: string | null;
            /** Format: decimal */
            lat: string;
            /** Format: decimal */
            lng: string;
            address: string;
        };
        AllCategoriesResponse: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
        };
        Conversation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly other: components["schemas"]["Participant"];
            reservation: components["schemas"]["ConversationReservation"];
        };
        ConversationItem: {
            name: string;
        };
        ConversationReservation: {
            /** Format: uuid */
            readonly id: string;
            item: components["schemas"]["ConversationItem"];
        };
        CreateItem: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            category: string;
            name: string;
            /** Format: decimal */
            price: string;
            /** Format: uri */
            cover: string;
            readonly images: components["schemas"]["ItemImages"][];
            /** Format: uuid */
            location: string;
        };
        CreateMessage: {
            content: string;
        };
        CreateReservation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            item: string;
            /** Format: date-time */
            from_date: string;
            /** Format: date-time */
            to_date: string;
            /** Format: uuid */
            readonly renter: string;
        };
        CreateReview: {
            content?: string | null;
            /** Format: double */
            point: number;
        };
        EditItem: {
            /** Format: uuid */
            category: string;
            name: string;
            /** Format: decimal */
            price: string;
            /** Format: uri */
            cover: string;
            /** Format: uuid */
            location: string;
            readonly images: components["schemas"]["ItemImages"][];
            kept_existing_images?: string[];
            /** Format: uri */
            existing_cover_url?: string;
        };
        InboxItem: {
            /** Format: uuid */
            readonly id: string;
            owner: components["schemas"]["InboxOwner"];
            name: string;
            /** Format: uri */
            cover: string;
            location: components["schemas"]["ReservationLocation"];
        };
        InboxOwner: {
            /** Format: uuid */
            readonly id: string;
        };
        ItemAvailabilty: {
            /** Format: date-time */
            from_date: string;
            /** Format: date-time */
            to_date: string;
        };
        ItemCategory: {
            /** Format: uuid */
            readonly id: string;
            name: string;
        };
        ItemImages: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uri */
            image: string;
        };
        ItemResponse: {
            /** Format: uuid */
            readonly id: string;
            category: components["schemas"]["ItemCategory"];
            name: string;
            /** Format: decimal */
            price: string;
            owner: components["schemas"]["UserData"];
            /** Format: uri */
            cover: string;
            location: components["schemas"]["LimitedLocation"];
            images: components["schemas"]["ItemImages"][];
            readonly reservations: components["schemas"]["ItemAvailabilty"][];
            readonly reviews: components["schemas"]["Review"][];
        };
        LimitedLocation: {
            /** Format: uuid */
            readonly id: string;
            address: string;
            /** Format: decimal */
            lat: string;
            /** Format: decimal */
            lng: string;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        MarkMessagesReadResponse: {
            /** @description Number of messages set to read */
            updated_count: number;
        };
        Message: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            conversation: string;
            sender: components["schemas"]["MessageSender"];
            content: string;
            is_read?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        MessageSender: {
            /** Format: email */
            email: string;
        };
        OwnItem: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: decimal */
            price: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uri */
            cover: string;
            /** Format: uuid */
            location: string;
            /** Format: uuid */
            category: string;
            images: components["schemas"]["ItemImages"][];
        };
        OwnLocation: {
            /** Format: uuid */
            readonly id: string;
            label?: string | null;
            address: string;
            /** Format: decimal */
            lat: string;
            /** Format: decimal */
            lng: string;
        };
        PaginatedItemResponseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ItemResponse"][];
        };
        PaginatedMessageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Message"][];
        };
        PaginatedStaffUsersList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StaffUsers"][];
        };
        Participant: {
            /** Format: uuid */
            readonly id: string;
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            /** Format: uri */
            profile_pic?: string | null;
        };
        PatchedAddEditLocation: {
            label?: string | null;
            /** Format: decimal */
            lat?: string;
            /** Format: decimal */
            lng?: string;
            address?: string;
        };
        PatchedEditItem: {
            /** Format: uuid */
            category?: string;
            name?: string;
            /** Format: decimal */
            price?: string;
            /** Format: uri */
            cover?: string;
            /** Format: uuid */
            location?: string;
            readonly images?: components["schemas"]["ItemImages"][];
            kept_existing_images?: string[];
            /** Format: uri */
            existing_cover_url?: string;
        };
        PatchedProfilePictureUpdate: {
            /** Format: uri */
            profile_pic?: string | null;
        };
        PatchedSetIsActive: {
            is_active?: boolean;
        };
        PatchedStatusChange: {
            /** Format: uuid */
            readonly id?: string;
            status?: components["schemas"]["StatusEnum"];
        };
        PatchedUserDataEdit: {
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email?: string;
        };
        ProfilePictureUpdate: {
            /** Format: uri */
            profile_pic?: string | null;
        };
        Register: {
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            password: string;
            password_confirmation: string;
        };
        ReservationItem: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            owner: components["schemas"]["ReservationUser"];
            /** Format: uri */
            cover: string;
            location: components["schemas"]["ReservationLocation"];
        };
        ReservationLocation: {
            /** Format: uuid */
            readonly id: string;
            address: string;
        };
        ReservationRequest: {
            /** Format: uuid */
            readonly id: string;
            item: components["schemas"]["InboxItem"];
            /** Format: date-time */
            from_date: string;
            /** Format: date-time */
            to_date: string;
            renter: components["schemas"]["ReservationUser"];
            /** Format: date-time */
            readonly created_at: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: decimal */
            total_price: string;
        };
        ReservationUser: {
            /** Format: uuid */
            readonly id: string;
            first_name: string;
            last_name: string;
            /** Format: uri */
            profile_pic?: string | null;
        };
        Review: {
            /** Format: uuid */
            readonly id: string;
            sender: components["schemas"]["ReviewUser"];
            content?: string | null;
            /** Format: decimal */
            point?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ReviewUser: {
            first_name: string;
            last_name: string;
            /** Format: uri */
            profile_pic?: string | null;
        };
        SetIsActive: {
            is_active?: boolean;
        };
        StaffUsers: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            is_active?: boolean;
            /** Format: uri */
            profile_pic?: string | null;
            /** Format: decimal */
            rating?: string;
        };
        StatusChange: {
            /** Format: uuid */
            readonly id: string;
            status?: components["schemas"]["StatusEnum"];
        };
        /**
         * @description * `PENDING` - Pending
         *     * `ACCEPTED` - Accepted
         *     * `REJECTED` - Rejected
         *     * `IN_PROGRESS` - In Progress
         *     * `RETURN_PENDING` - Return Pending
         *     * `COMPLETED` - Completed
         * @enum {string}
         */
        StatusEnum: "PENDING" | "ACCEPTED" | "REJECTED" | "IN_PROGRESS" | "RETURN_PENDING" | "COMPLETED";
        SuccessResponse: {
            message: string;
        };
        UserData: {
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            /** Format: uri */
            profile_pic?: string | null;
            /** Format: decimal */
            rating?: string;
            rating_count?: number;
            is_staff?: boolean;
        };
        UserDataEdit: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
        };
        UserReservation: {
            /** Format: uuid */
            readonly id: string;
            item: components["schemas"]["ReservationItem"];
            /** Format: uuid */
            renter: string;
            /** Format: date-time */
            from_date: string;
            /** Format: date-time */
            to_date: string;
            /** Format: date-time */
            readonly created_at: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: decimal */
            total_price: string;
        };
        UserResponse: {
            user: components["schemas"]["UserData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    categories_all_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllCategoriesResponse"][];
                };
            };
        };
    };
    chat_conversations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
        };
    };
    chat_conversations_messages_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessageList"];
                };
            };
        };
    };
    chat_conversations_messages_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessage"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateMessage"];
                "multipart/form-data": components["schemas"]["CreateMessage"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMessage"];
                };
            };
        };
    };
    chat_conversations_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkMessagesReadResponse"];
                };
            };
        };
    };
    items_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    items_all_list: {
        parameters: {
            query?: {
                /** @description Multiple values may be separated by commas. */
                category?: string[];
                /** @description User latitude */
                lat?: number;
                /** @description User longitude */
                lng?: number;
                max_price?: number;
                min_price?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedItemResponseList"];
                };
            };
        };
    };
    items_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateItem"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateItem"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateItem"];
                };
            };
        };
    };
    items_delete_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    items_edit_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["EditItem"];
                "application/x-www-form-urlencoded": components["schemas"]["EditItem"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditItem"];
                };
            };
        };
    };
    items_edit_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedEditItem"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEditItem"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditItem"];
                };
            };
        };
    };
    reservations_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservation"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateReservation"];
                "multipart/form-data": components["schemas"]["CreateReservation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateReservation"];
                };
            };
        };
    };
    reservations_get_list: {
        parameters: {
            query: {
                tab: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReservation"][];
                };
            };
        };
    };
    reservations_get_requests_list: {
        parameters: {
            query: {
                tab: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRequest"][];
                };
            };
        };
    };
    reservations_update_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
                "application/x-www-form-urlencoded": components["schemas"]["StatusChange"];
                "multipart/form-data": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChange"];
                };
            };
        };
    };
    reservations_update_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStatusChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStatusChange"];
                "multipart/form-data": components["schemas"]["PatchedStatusChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChange"];
                };
            };
        };
    };
    reviews_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReview"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateReview"];
                "multipart/form-data": components["schemas"]["CreateReview"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateReview"];
                };
            };
        };
    };
    users_suspend_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SetIsActive"];
                "application/x-www-form-urlencoded": components["schemas"]["SetIsActive"];
                "multipart/form-data": components["schemas"]["SetIsActive"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetIsActive"];
                };
            };
        };
    };
    users_suspend_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSetIsActive"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSetIsActive"];
                "multipart/form-data": components["schemas"]["PatchedSetIsActive"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetIsActive"];
                };
            };
        };
    };
    users_add_location_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddEditLocation"];
                "application/x-www-form-urlencoded": components["schemas"]["AddEditLocation"];
                "multipart/form-data": components["schemas"]["AddEditLocation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddEditLocation"];
                };
            };
        };
    };
    users_all_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStaffUsersList"];
                };
            };
        };
    };
    users_delete_location_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_edit_location_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddEditLocation"];
                "application/x-www-form-urlencoded": components["schemas"]["AddEditLocation"];
                "multipart/form-data": components["schemas"]["AddEditLocation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddEditLocation"];
                };
            };
        };
    };
    users_edit_location_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAddEditLocation"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAddEditLocation"];
                "multipart/form-data": components["schemas"]["PatchedAddEditLocation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddEditLocation"];
                };
            };
        };
    };
    users_items_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnItem"][];
                };
            };
        };
    };
    users_locations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnLocation"][];
                };
            };
        };
    };
    users_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    users_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    users_refresh_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    users_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    users_reviews_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
        };
    };
    users_update_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDataEdit"];
                "application/x-www-form-urlencoded": components["schemas"]["UserDataEdit"];
                "multipart/form-data": components["schemas"]["UserDataEdit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataEdit"];
                };
            };
        };
    };
    users_update_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserDataEdit"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserDataEdit"];
                "multipart/form-data": components["schemas"]["PatchedUserDataEdit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataEdit"];
                };
            };
        };
    };
    users_update_profilepic_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["ProfilePictureUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["ProfilePictureUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePictureUpdate"];
                };
            };
        };
    };
    users_update_profilepic_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedProfilePictureUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfilePictureUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePictureUpdate"];
                };
            };
        };
    };
}
