# Generated by Django 6.0.1 on 2026-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_receiver_review_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='point',
            field=models.FloatField(default=0.0),
        ),
    ]
