# Generated by Django 6.0.1 on 2026-03-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='point',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
